# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Whenever a change is made to the master branch
trigger:
- master

# using ubuntu latest vmImage
pool:
  vmImage: 'ubuntu-latest'

pr: 'none'



stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'Project0'
              organization: 'testkey12345'
              scannerMode: 'MSBuild'
              projectKey: 'thisIsMyProjectKey'
              projectName: 'project0'
              extraProperties: |
                sonar.exclusions=**/obj/**,**/*.dll
                sonar.branch.name=$(Build.SourceBranchName)
                sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
                sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/*.xml
          - script: dotnet build 'Proj0/Proj0/Proj0.sln'
          - script: echo 'Project built'
          - task: DotNetCoreCLI@2
            displayName: dotnet test
            inputs:
              command: 'test'
              arguments: '--configuration $(BuildConfiguration) 
                /p:CollectCoverage=true 
                /p:CoverletOutputFormat=opencover 
                /p:Coverletoutput=$(Build.SourcesDirector)/TestResults/Coverage 
                --logger trx'
              projects: '**/*XUnitTest_proj0.csproj'
              nobuild: true
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Build.SourcesDirectory)/**/*.xml'
              reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage' 
          - task: SonarCloudAnalyze@1
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
          - script: dotnet publish 'Proj0/Proj0/Proj0.sln'