# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Whenever a change is made to the master branch
trigger:
- master

# using ubuntu latest vmImage
pool:
  vmImage: 'ubuntu-latest'

pr: 'none'

stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'proj0'
              organization: 'firstsonar2020'
              scannerMode: 'MSBuild'
              projectKey: '0f92f5207f7f0b675eac0a8c86988fbb04241c8a'
              projectName: 'proj0'
          - script: dotnet build 'Proj0/Proj0/Proj0.sln'
          - script: echo 'Project built'
          - script: dotnet test 'Proj0/XUnitTest_proj0/XUnitTest_proj0.csproj'
          - script: echo 'tests run'
          - task: PublishCodeCoverageResults@1
            inputs:
              summaryFileLocation: Proj0/XUnitTest_proj0/TestResults/72941aa6-0220-4728-affa-a062e6dd5674/coverage.cobertura.xml
          - task: SonarCloudAnalyze@1
      - job: 'publish'
        dependsOn: 'build'
        steps:
          - script: dotnet publish 'Proj0/Proj0/Proj0.sln'