trigger: #  pipeline will auto run when any changes to the master branch are made
- master

# using ubuntu latest vmImage
pool:
  vmImage: 'ubuntu-latest'

pr: 'none'

stages:
  - stage:
    jobs:
      - job: 'build'
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'MyProj'
              organization: 'neworganization'
              scannerMode: 'MSBuild'
              projectKey: 'a60f87ac3439f702e9a4a3ffe85a209258a90e90'
              projectName: 'myProjKey'
              extraProperties: |
                sonar.exclusions=**/obj/**,**/*.dll
                                sonar.branch.name=$(Build.SourceBranchName)
                                sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx
                                sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/*.xml
          - script: dotnet build 'Proj0/Proj0/Proj0.sln'
          - task: DotNetCoreCLI@2
            displayName: dotnet test
            inputs:
              command: 'test'
              arguments: '--configuration $(BuildConfiguration) 
              /p:CollectCoverage=true /p:CoverletOutputFormat=opencover 
              /p:Coverletoutput=$(Build.SourcesDirector)/TestResults/Coverage 
              --logger trx'
              projects: '**/*XUnitTest_proj0.csproj'
              nobuild: true
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(Build.SourcesDirectory)/**/*.xml'
              reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage' 
          - task: SonarCloudAnalyze@1
          - script: dotnet publish 'Proj0/Proj0/Proj0.sln'
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'