//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace XUnitTest_proj0
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<__EFMigrationsHistory>();
                db.CreateTable<Customers>();
                db.CreateTable<Locations>();
                db.CreateTable<Order>();
                db.CreateTable<OrderDetails>();
                db.CreateTable<Products>();
            }
        }
    }
    public partial class __EFMigrationsHistory
    {
        [PrimaryKey]
        public String MigrationId { get; set; }
        
        [NotNull]
        public String ProductVersion { get; set; }
        
    }
    
    public partial class Customers
    {
        [PrimaryKey, AutoIncrement]
        public Int64 CustomerId { get; set; }
        
        [NotNull]
        public String FName { get; set; }
        
        [NotNull]
        public String LName { get; set; }
        
        [NotNull]
        public String PhoneNum { get; set; }
        
        [NotNull]
        public Int64 PreferredLoc { get; set; }
        
    }
    
    public partial class Locations
    {
        [PrimaryKey, AutoIncrement]
        public Int64 LocationId { get; set; }
        
        [NotNull]
        public String LocName { get; set; }
        
    }
    
    public partial class Order
    {
        [PrimaryKey, AutoIncrement]
        public Int64 OrderId { get; set; }
        
        [NotNull]
        public Int64 CustomerId { get; set; }
        
        [NotNull]
        public Int64 LocationId { get; set; }
        
        public String TimeStamp { get; set; }
        
        [NotNull]
        public Double Total { get; set; }
        
    }
    
    public partial class OrderDetails
    {
        [PrimaryKey, AutoIncrement]
        public Int64 OrderDetailsId { get; set; }
        
        [NotNull]
        public Int64 OrderId { get; set; }
        
        [NotNull]
        public Int64 ProductId { get; set; }
        
        [NotNull]
        public Int64 Qty { get; set; }
        
    }
    
    public partial class Products
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ProductId { get; set; }
        
        [NotNull]
        public Int64 LocationId { get; set; }
        
        [NotNull]
        public String ProductName { get; set; }
        
        [NotNull]
        public Double UnitCost { get; set; }
        
        [NotNull]
        public Int64 Quantity { get; set; }
        
    }
    
}
